Food layout
martyn-fanclub/android-2022 pull request #8
Opened 2022-04-08 16:31 UTC by coradead

2022-04-08 19:52 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/models/Food.kt
> +    val price: Int,
Решили, что тут BigDecimal. Просьба поправить

2022-04-08 19:53 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodFragment.kt
> +import java.util.*
![image](https://user-images.githubusercontent.com/76079492/162517035-e21a40dd-b987-4229-ba2c-7ba296c049c9.png)

2022-04-08 19:54 UTC, PaaavelZ commented on app/src/main/res/values-ru/strings.xml
> +    <string name="app_name">Рестаран</string>
![image](https://user-images.githubusercontent.com/76079492/162517222-7c93f062-f17c-4a3f-ae1f-8b4cc73faf7f.png)

2022-04-08 19:56 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodFragment.kt
> +//        val adapter = FoodAdapter(Collections.emptyList())
Что за комментарии?

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +        var imageView: ImageView = itemView.findViewById(R.id.iv_foodPicture)
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +        val foodName: TextView = itemView.findViewById(R.id.tv_foodName)
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +        val foodWeight: TextView = itemView.findViewById(R.id.tv_foodWeight)
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +        val buttonFoodPrice: Button = itemView.findViewById(R.id.bt_foodPrice)
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +            android:id="@+id/iv_foodPicture"
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +                android:id="@+id/tv_foodName"
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +                android:id="@+id/tv_foodWeight"
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +                android:id="@+id/bt_foodPrice"
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/fragment_food.xml
> +        android:id="@+id/rv_foodList"
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/values-ru/strings.xml
> +    <string name="buttonPrice">Ошибка загрузки</string>
неожиданный camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/values/strings.xml
> +    <string name="buttonPrice">Price error</string>
неожиданный camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +                app:layout_constraintTop_toBottomOf="@+id/tv_foodWeight" />
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +                app:layout_constraintTop_toBottomOf="@+id/tv_foodName" />
snake case + camel case

2022-04-08 20:12 UTC, PaaavelZ commented on app/src/main/res/layout/food_item.xml
> +                android:text="@string/buttonPrice"
неожиданный camel case

2022-04-11 12:49 UTC, pasha010 commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +class FoodAdapter(var foodList: List<Food>) : RecyclerView.Adapter<FoodAdapter.FoodViewHolder>() {
юзайте ListAdapter

2022-04-11 16:19 UTC, Pobedos commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodFragment.kt
> +import java.util.*
Ахахахах

2022-05-05 12:10 UTC, PaaavelZ requested changes
Test

2022-05-05 12:12 UTC, PaaavelZ approved these changes

2022-05-05 12:13 UTC, merged