Style refactor
martyn-fanclub/android-2022 pull request #9
Opened 2022-05-05 11:34 UTC by coradead

2022-05-05 11:37 UTC, coradead commented
Check this only after https://github.com/martyn-fanclub/android-2022/pull/8

2022-05-05 12:14 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/models/User.kt
> +)
Стиль?

2022-05-05 12:14 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/profile/ProfileFragment.kt
> +@file:Suppress("unused")
Почему подавляем?

2022-05-05 12:16 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/models/Food.kt
>  )
Где-то есть завершающая пустая строчка, где-то нет. Предлагаю добавить её здесь и во все остальные файлы, изменяемые этим пр'ом.

2022-05-05 12:17 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/models/Food.kt
>  )
Где-то есть завершающая пустая строчка, где-то нет. Предлагаю добавить её здесь и во всех остальных изменяемых этим ПРом файлах.

2022-05-05 12:20 UTC, PaaavelZ commented on app/src/main/res/values-ru/strings.xml
> +    <string name="food_weight_template">%1s гр.</string>
Почему в этом файле строчек меньше, чем в values/strings.xml?

2022-05-05 12:22 UTC, PaaavelZ commented on app/src/main/res/values/strings.xml
> +    <string name="price_sum_template" translatable="false">%1$d * %2$s ₽</string>
Рубли? В иностранной-то валюте?

2022-05-05 12:25 UTC, PaaavelZ requested changes

2022-05-05 12:25 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +                // FIXME set default img
Что это?

2022-05-05 12:25 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodFragment.kt
> +        TODO open description.
Кем TODO?

2022-05-05 13:47 UTC, coradead commented on app/src/main/java/com/old/leopards/restaurant/ui/models/User.kt
> +)
так читабельней

2022-05-05 13:47 UTC, coradead commented on app/src/main/java/com/old/leopards/restaurant/ui/profile/ProfileFragment.kt
> +@file:Suppress("unused")
потому что пока никто не использует

2022-05-05 13:48 UTC, coradead commented on app/src/main/java/com/old/leopards/restaurant/models/Food.kt
>  )
я эти занимался, видимо пропустил

2022-05-05 13:48 UTC, coradead commented on app/src/main/res/values-ru/strings.xml
> +    <string name="food_weight_template">%1s гр.</string>
не все переводится

2022-05-05 13:49 UTC, coradead commented on app/src/main/res/values/strings.xml
> +    <string name="price_sum_template" translatable="false">%1$d * %2$s ₽</string>
Ты же в России покупаешь, у нас только рублями можно

2022-05-05 13:49 UTC, coradead commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +                // FIXME set default img
Это для будущих поколений, я попрошу кого-нибудь, чтобы дизайн сделали

2022-05-05 13:50 UTC, coradead commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodFragment.kt
> +        TODO open description.
кем-то но не мне

2022-05-05 15:55 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/profile/ProfileFragment.kt
> +@file:Suppress("unused")
Кого не использует? Весь класс?

2022-05-05 15:59 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodAdapter.kt
> +                // FIXME set default img
Об этом надо сообщить в нашу беседу

2022-05-05 15:59 UTC, avramirs commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodFragment.kt
> +        TODO open description.
И об этом тоже

2022-05-10 08:07 UTC, PaaavelZ commented on app/src/main/java/com/old/leopards/restaurant/ui/food/FoodViewModel.kt
> +                    "[etnnj] с вареными яйцами",
Что за [etnnj]?

2022-05-10 15:24 UTC, artem24630 requested changes

2022-05-10 15:24 UTC, artem24630 commented on app/src/main/java/com/old/leopards/restaurant/models/Food.kt
> +    val img: Int?
так как мы будем получать картинку по интернету, то нам не drawable нужны, а скорее url

2022-05-12 08:14 UTC, PaaavelZ requested changes

2022-05-12 08:14 UTC, PaaavelZ commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.fragment.app.FragmentContainerView
Fragment

2022-05-13 15:05 UTC, avramirs approved these changes

2022-05-13 15:06 UTC, merged